name: Automated Test Suite

on: [push]

jobs:
  specs:
    runs-on: ubuntu-latest
    env:
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Test with RSpec
        env:
          RUBYOPT: "-W:no-deprecated -W:no-experimental"
        run: |
          bundle exec rspec ./spec --fail-fast
